# Generated by Django 5.1.1 on 2024-09-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingdata',
            unique_together={('bank_name', 'year', 'month', 'date', 'sale_total', 'sale_amount')},
        ),
    ]
